name = "training-platform"
main = "src/index.tsx"
compatibility_date = "2025-10-28"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

[[ d1_databases ]]
binding = "DB"
database_name = "training-platform-production"
database_id = "local-dev"
